### ISSUE TITLE
项目结构有案例么？

### ISSUE THREAD

**Issue by stevenkitter** [unknwon/go-code-convention#3]
无闻大神 麻烦提供一下项目案例的仓库 供学习

**Comment by unknwon** [comment]
我觉得没有必要吧，项目结构是根据项目大小和团队协作方式、模块职能划分来的，很难有统一的标准。

**Comment by unknwon** [comment]
不过可以多看一些自己感兴趣的开源项目，然后参考一下他们的项目结构
